### ISSUE TITLE
Feedback week 1

### ISSUE THREAD

**Issue by johancvb** [HappyPantss/progressive-web-apps-2021#1]
Yoo!

Goed om te zien dat je app (in tegenstelling tot die van mij 😅) al een overview pagina rendert!
Ik zal je code bekijken en evt. feedback en tips geven.

Ik zie dat je nog je oude WAFS files en code in je src-mapje staan, zoals je JavaScript en Routie enz.
Volgens mij kan je dit verwijderen, aangezien je het niet meer hoeft te gebruiken. Maar ik snap dat het misschien voor het schrijven van je code handig is als referentie.

Ik zou ook je post.ejs & posts.ejs renamen, aangezien je nu met hero's werkt 😅

Voor de rest heb al je een strakke code, en rendert je overview pagina al data. 

Ik zie als je je hero-foto wilt inladen, dat je in de code nog gebruik maakt van bijvoorbeeld ${...}, terwijl dit nu natuurlijk met ejs moet. Dit weet je zelf ook waarschijnlijk wel, maar had je er nog geen tijd voor gehad. 

Ook kun je misschien proberen om met .forEach door je API-data te loopen, om zo de andere heroes te renderen.

Als laatste zou ik een readme aanmaken waar je je voortgang bij kan houden en uit kan leggen hoe je bijvoorbeeld de node packages installeerd.

Overall: keep coding!! Ziet er al goed uit, en ik zie dat je weet wat je doet 😉.

-- Johan ✌

**Comment by HappyPantss** [comment]
Erg goede feedback Johan, thanks! Ik wist inderdaad dat bv ${...} niet zou werken haha, en dat heb ik op een aantal plekken al veranderd! Ik ga met alles zo snel mogelijk aan de gang.

**Comment by HappyPantss** [comment]
Ik heb alle feedback verwerkt. Nog bedankt!
