### ISSUE TITLE
Feedback week 1

### ISSUE THREAD

**Issue by decrek** [HappyPantss/progressive-web-apps-2021#2]
He Sergio!

Je bent op de goede weg! Je overzichtspagina wordt gerendered, maar je detail route staat nog uitgecomment. Probeer deze ook aan de praat te krijgen. Je readme is duidelijk voor als je het lokaal wilt gebruiken, maar misschien kan je nog een beetje je app en werking ervan beschrijven.

Probeer daarnaast nog wat basic tooling op te zetten.

Je emojis in je commits zijn 💯  btw!

Succes!

**Comment by HappyPantss** [comment]
Hi Declan, bedankt voor je feedback! Ik heb alles verwerkt waar nodig.
